### ISSUE TITLE
Add dataset versioning

### ISSUE THREAD

**Issue by mitchelloharawild** [mitchelloharawild/roam#4]
Allow users to install a specific version of a dataset, if the obtainer function supports it.

**Comment by FinYang** [comment]
Package writer: someone who uses `roam` to write packages.
User: someone who uses the package Package writer wrote (not `roam`).

- [x] Restrict the first argument of the obtainer function to be the version number user wants to install
- [x] In the `roam_install` function, allow user to specify which version they want to install, which we pass to the obtainer function. If unspecified, we pass `NULL` so the obtainer knows to install the latest version
- [x] Provide a `roam_version` function to package writer, which they can use in the obtainer function to specify the currently downloaded version number, which we save to a text file in the cache folder
- [x] `roam_update` is a wrapper around `roam_install` which passes `NULL` as the version number to install the latest version.
